db:
  values: '{url:''https://myurl-testdb.com'',username:''abdul'',password:''test-1234''}'
  port: '1200'
  host: 10.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: config.demo
server:
  port: '9090'
my:
  greeting: hello spring at quince
  list:
    values: one,two,three